version: "2"

services:
    balancer:
        image: markamdev/goloba
        build:
            context: .
            dockerfile: Dockerfile.goloba
        environment:
            - GOLOBA_PORT=8000
            - GOLOBA_TARGETS="dummy.server1:9001;dummy.server2:9002"
        networks:
            - glbtesting
        ports:
            - 8080:8000
        depends_on:
            - dummy.server1
            - dummy.server2


    dummy.server1:
        image: markamdev/dummyserver
        build:
            context: .
            dockerfile: Dockerfile.dummyserver
        environment:
            - DUMMY_PORT=9001
            - DUMMY_MESSAGE="Hi there from server1"
        networks:
            - glbtesting

    dummy.server2:
        image: markamdev/dummyserver
        build:
            context: .
            dockerfile: Dockerfile.dummyserver
        environment:
            - DUMMY_PORT=9002
            - DUMMY_MESSAGE="Hi there from server2"
        networks:
            - glbtesting

networks:
    glbtesting:
