# --- build application
FROM golang:1.14 AS builder
WORKDIR /temp
COPY . .

RUN make goloba

# --- create image
FROM ubuntu:20.04

WORKDIR /usr/bin
COPY --from=builder /temp/build/goloba .

EXPOSE 8000

ENV PORT=8000 TARGETS="dummy1:9001,dummy2:9002"

CMD [ "/usr/bin/goloba" ]
