# --- build application
FROM golang:1.14 AS builder
WORKDIR /temp
COPY . .
RUN make dummyserver

# --- create image
FROM ubuntu:20.04

WORKDIR /usr/bin
COPY --from=builder /temp/build/dummyserver .

EXPOSE 9001

ENV PORT=9001
ENV MESSAGE="DummyServer in Docker"

CMD [ "/usr/bin/dummyserver" ]
