# --- build application
FROM golang:1.14 AS builder
WORKDIR /temp
COPY . .

RUN GOOS=linux GOARCH=arm make goloba

# --- create image
FROM arm32v7/ubuntu:20.04

WORKDIR /usr/bin
COPY --from=builder /temp/build/goloba .

EXPOSE 8000

ENV GOLOBA_PORT=8000 GOLOBA_TARGETS="dummy1:9001;dummy2:9002"

CMD [ "/usr/bin/goloba","-log-stdout" ]
