# --- build application
FROM golang:1.14 AS builder
WORKDIR /temp
COPY . .
RUN make dummyserver

# --- create image
FROM arm32v7/ubuntu:20.04

WORKDIR /usr/bin
COPY --from=builder /temp/build/dummyserver .

EXPOSE 9001

ENV DUMMY_PORT=9001

CMD [ "/usr/bin/dummyserver" ]
